names = {
    'zhuhai':{
      'HS': {
        'name_cn': 'EL划伤',
        'name_en': 'EL_HS'},
      'HBN': {
        'name_cn': 'EL黑斑',
        'name_en': 'EL_HBN'},
      'WZFH': {
        'name_cn': 'EL雾状发黑',
        'name_en': 'EL_WZFH'},
      'HLY': {
        'name_cn': 'EL花篮印',
        'name_en': 'EL_HLY'},
      'LXDS': {
        'name_cn': 'EL连续断栅',
        'name_en': 'EL_LXDS'},
      'DL': {
        'name_cn': 'EL短路',
        'name_en': 'EL_DL'},
      'MD': {
        'name_cn': 'EL麻点',
        'name_en': 'EL_MD'},
      'ZCY': {
        'name_cn': 'EL舟齿印',
        'name_en': 'EL_ZCY'},
      'HB': {
        'name_cn': 'EL黑边',
        'name_en': 'EL_HB'},
      'ZKY': {
        'name_cn': 'EL舟框印',
        'name_en': 'EL_ZKY'},
      'TXY': {
        'name_cn': 'EL同心圆',
        'name_en': 'EL_TXY'},
      'WR': {
        'name_cn': 'EL污染',
        'name_en': 'EL_WR'},
      'HD': {
        'name_cn': 'EL黑点',
        'name_en': 'EL_HD'},
      'YL': {
        'name_cn': 'EL隐裂',
        'name_en': 'EL_YL'},
      'SJFH': {
        'name_cn': 'EL四角发黑',
        'name_en': 'EL_SJFH'},
      'HX': {
        'name_cn': 'EL黑线',
        'name_en': 'EL_HX'},
      'DS': {
        'name_cn': 'EL断栅',
        'name_en': 'EL_DS'},
      'GK': {
        'name_cn': 'EL过刻',
        'name_en': 'EL_GK'},
      'SY': {
        'name_cn': 'EL水印',
        'name_en': 'EL_SY'},
      'QLP': {
        'name_cn': 'EL气流片',
        'name_en': 'EL_QLP'},
      'LXHS': {
        'name_cn': 'EL连续断栅',
        'name_en': 'EL_LXHS'},
      'XPY': {
        'name_cn': 'EL吸盘印',
        'name_en': 'EL_XPY'},
      'KDY': {
        'name_cn': 'EL卡点印',
        'name_en': 'EL_KDY'},
      'SZY': {
        'name_cn': 'EL手指印',
        'name_en': 'EL_SZY'}
    },
    '4c':{
      'LXDS': {
        'name_cn': 'EL断栅',
        'name_en': 'EL_DS'},
      'HD': {
        'name_cn': 'EL黑斑黑点',
        'name_en': 'EL_HBHD'},
      'WZFH': {
        'name_cn': 'EL雾状发黑',
        'name_en': 'EL_WZFH'},
      'PY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'PDY1': {
        'name_cn': 'EL滚轮印',
        'name_en': 'EL_GLY'},
      'DS': {
        'name_cn': 'EL断栅',
        'name_en': 'EL_DS'},
      'GLY': {
        'name_cn': 'EL滚轮印',
        'name_en': 'EL_GLY'},
      'XPY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'SY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'QLP': {
        'name_cn': 'EL气流片',
        'name_en': 'EL_QLP'},
      'BCGS': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'MD': {
        'name_cn': 'EL黑斑黑点',
        'name_en': 'EL_HBHD'},
      'HS': {
        'name_cn': 'EL划伤',
        'name_en': 'EL_HS'},
      'PDY': {
        'name_cn': 'EL滚轮印',
        'name_en': 'EL_GLY'},
      'QHB': {
        'name_cn': 'EL黑边',
        'name_en': 'EL_HB'},
      'GK': {
        'name_cn': 'EL过刻',
        'name_en': 'EL_GK'},
      'TXY': {
        'name_cn': 'EL同心圆',
        'name_en': 'EL_TXY'},
      'HBN': {
        'name_cn': 'EL黑斑黑点',
        'name_en': 'EL_HBHD'},
      'HJ': {
        'name_cn': 'EL黑边',
        'name_en': 'EL_HB'},
      'HB': {
        'name_cn': 'EL黑边',
        'name_en': 'EL_HB'},
      'YL': {
        'name_cn': 'EL隐裂',
        'name_en': 'EL_YL'},
      'ZKY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'DJPY': {
        'name_cn': 'EL断栅',
        'name_en': 'EL_DS'},
      'ZCY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'BJFH': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'SMZHS': {
        'name_cn': 'EL划伤',
        'name_en': 'EL_HS'},
      'LXHS': {
        'name_cn': 'EL划伤',
        'name_en': 'EL_HS'},
      'KDY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'LX': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'BDJFH': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'HX': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'CXYC': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'ZSYH': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'},
      'BJPY': {
        'name_cn': 'EL可信度',
        'name_en': 'EL_KXD'}
    }
}
